# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-04 12:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('history', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hurricanepoint',
            name='parent',
        ),
        migrations.AddField(
            model_name='hurricane',
            name='points',
            field=models.ManyToManyField(to='history.HurricanePoint'),
        ),
    ]
