# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-04 14:47
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('history', '0003_auto_20171104_1342'),
    ]

    operations = [
        migrations.AddField(
            model_name='hurricane',
            name='category',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='hurricane',
            name='max_wind',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='hurricane',
            name='start_date',
            field=models.DateTimeField(default=datetime.datetime(2017, 11, 4, 14, 47, 55, 682237)),
            preserve_default=False,
        ),
    ]
